from __future__ import annotations

import hashlib
from datetime import date, datetime, timezone
from zoneinfo import ZoneInfo

import pytest

import historical_analysis as ha
from analysis_log import parse_records
from historical_analysis import (
    INCOMPLETE_NAME,
    _acquire_conversion_lock,
    convert_completed_logs,
    project_legacy,
)


def _source(day: str, text: str = "work") -> str:
    return f"""# Work Log - {day}

> Auto-generated by Interleaved Logger v4.1.0

---

## App - Window
*10:00:00*

{text}

---

"""


def test_historical_export_is_private_reversible_and_compact(tmp_path):
    log_dir = tmp_path / "logs"
    output_dir = tmp_path / "private_review"
    log_dir.mkdir()
    source = log_dir / "daily_log_2026-08-22.md"
    source_text = """# Work Log - 2026-08-22

> Auto-generated by Interleaved Logger v4.1.0

---

## App - Window
*10:00:00*

typed work

🖱️ **Клік:** Button 'Save'

---

## App - Window
*10:00:30*

🖱️ **Клік:** Button 'Save'

> [CLIPBOARD]:
```text
line one

## content, not a section
```

---

"""
    source.write_text(source_text, encoding="utf-8")
    (log_dir / "daily_log_2026-08-23.md").write_text(
        _source("2026-08-23", "active"), encoding="utf-8"
    )
    original_digest = hashlib.sha256(source.read_bytes()).hexdigest()

    results = convert_completed_logs(
        log_dir, output_dir, today=date(2026, 8, 23)
    )

    assert len(results) == 1
    result = results[0]
    assert result.source_sections == 2
    assert result.output_context_groups == 1
    assert result.exact_repeats_collapsed == 1
    assert result.inferred_kinds == {
        "click": 2,
        "clipboard": 1,
        "type": 1,
    }
    assert hashlib.sha256(source.read_bytes()).hexdigest() == original_digest
    output = output_dir / "historical_analysis_2026-08-22.md"
    output_text = output.read_text(encoding="utf-8")
    assert "section-boundaries=inferred" in output_text
    records = parse_records(output_text)
    assert [record.kind for record in records] == [
        "type",
        "click",
        "click",
        "clipboard",
    ]
    assert records[-1].payload == "line one\n\n## content, not a section"
    assert output.stat().st_mode & 0o777 == 0o600
    assert output_dir.stat().st_mode & 0o777 == 0o700
    assert (output_dir / "conversion_summary.json").stat().st_mode & 0o777 == 0o600
    assert (output_dir / "README.txt").stat().st_mode & 0o777 == 0o600
    assert not (output_dir / INCOMPLETE_NAME).exists()
    assert not (output_dir / "historical_analysis_2026-08-23.md").exists()
    assert not any(path.name.startswith("daily_log_") for path in output_dir.iterdir())

    first_output_digest = hashlib.sha256(output.read_bytes()).hexdigest()
    convert_completed_logs(log_dir, output_dir, today=date(2026, 8, 23))
    assert hashlib.sha256(output.read_bytes()).hexdigest() == first_output_digest


def test_historical_export_refuses_the_live_log_tree(tmp_path):
    log_dir = tmp_path / "logs"
    log_dir.mkdir()
    with pytest.raises(ValueError, match="separate"):
        convert_completed_logs(log_dir, log_dir / "review")
    with pytest.raises(ValueError, match="separate"):
        convert_completed_logs(log_dir, tmp_path)


def test_projection_preserves_unicode_blank_spans_and_internal_separator():
    payload = "alpha\u0085beta\u2028gamma\u2029delta\n\n\n---\n\n\nomega"
    source = _source("2026-08-22", payload)
    records, sections, ambiguous, _dst, merged, _generator = project_legacy(
        source, date(2026, 8, 22), ZoneInfo("Europe/Zagreb")
    )
    assert sections == 1
    assert ambiguous == 0
    assert merged == 2
    assert len(records) == 1
    assert records[0].payload == payload


@pytest.mark.parametrize(
    ("source", "message"),
    (
        (_source("2026-08-21"), "header date"),
        (_source("2026-08-22", "before\n\n## fake\n*11:00:00*\n\nafter"), "preceded"),
        (
            _source("2026-08-22", "> [CLIPBOARD]:\n```text\nunclosed"),
            "unclosed generated event fence",
        ),
    ),
)
def test_projection_rejects_ambiguous_legacy_structure(source, message):
    with pytest.raises(ValueError, match=message):
        project_legacy(source, date(2026, 8, 22), ZoneInfo("Europe/Zagreb"))


def test_failed_rerun_stays_marked_until_every_day_is_coherent(tmp_path):
    log_dir = tmp_path / "logs"
    output_dir = tmp_path / "private_review"
    log_dir.mkdir()
    first = log_dir / "daily_log_2026-08-21.md"
    second = log_dir / "daily_log_2026-08-22.md"
    first.write_text(_source("2026-08-21", "first"), encoding="utf-8")
    second.write_text(_source("2026-08-22", "second"), encoding="utf-8")
    convert_completed_logs(log_dir, output_dir, today=date(2026, 8, 23))
    old_summary = (output_dir / "conversion_summary.json").read_bytes()

    first.write_text(_source("2026-08-21", "changed"), encoding="utf-8")
    second.write_bytes(b"\xff")
    with pytest.raises(UnicodeDecodeError):
        convert_completed_logs(log_dir, output_dir, today=date(2026, 8, 23))
    assert (output_dir / INCOMPLETE_NAME).is_file()
    assert (output_dir / "conversion_summary.json").read_bytes() == old_summary

    second.write_text(_source("2026-08-22", "repaired"), encoding="utf-8")
    convert_completed_logs(log_dir, output_dir, today=date(2026, 8, 23))
    assert not (output_dir / INCOMPLETE_NAME).exists()
    assert (output_dir / "conversion_summary.json").read_bytes() != old_summary


def test_deleted_source_is_reported_without_deleting_its_private_copy(tmp_path):
    log_dir = tmp_path / "logs"
    output_dir = tmp_path / "private_review"
    log_dir.mkdir()
    first = log_dir / "daily_log_2026-08-21.md"
    second = log_dir / "daily_log_2026-08-22.md"
    first.write_text(_source("2026-08-21"), encoding="utf-8")
    second.write_text(_source("2026-08-22"), encoding="utf-8")
    convert_completed_logs(log_dir, output_dir, today=date(2026, 8, 23))
    orphan = output_dir / "historical_analysis_2026-08-21.md"

    first.unlink()
    with pytest.raises(OSError, match="operator archive or deletion"):
        convert_completed_logs(log_dir, output_dir, today=date(2026, 8, 23))
    assert orphan.is_file()
    marker = (output_dir / INCOMPLETE_NAME).read_text(encoding="utf-8")
    assert orphan.name in marker


def test_concurrent_run_fails_before_it_changes_outputs(tmp_path):
    log_dir = tmp_path / "logs"
    output_dir = tmp_path / "private_review"
    log_dir.mkdir()
    (log_dir / "daily_log_2026-08-22.md").write_text(
        _source("2026-08-22"), encoding="utf-8"
    )
    convert_completed_logs(log_dir, output_dir, today=date(2026, 8, 23))
    summary = (output_dir / "conversion_summary.json").read_bytes()
    lock_fd = _acquire_conversion_lock(output_dir)
    try:
        with pytest.raises(OSError, match="another historical conversion"):
            convert_completed_logs(log_dir, output_dir, today=date(2026, 8, 23))
    finally:
        import fcntl
        import os

        fcntl.flock(lock_fd, fcntl.LOCK_UN)
        os.close(lock_fd)
    assert (output_dir / "conversion_summary.json").read_bytes() == summary
    assert not (output_dir / INCOMPLETE_NAME).exists()


def test_active_day_uses_the_configured_source_timezone(tmp_path, monkeypatch):
    class FixedDatetime(datetime):
        @classmethod
        def now(cls, tz=None):
            instant = datetime(2026, 8, 23, 1, 30, tzinfo=timezone.utc)
            return instant.astimezone(tz) if tz is not None else instant

    log_dir = tmp_path / "logs"
    output_dir = tmp_path / "private_review"
    log_dir.mkdir()
    (log_dir / "daily_log_2026-08-22.md").write_text(
        _source("2026-08-22"), encoding="utf-8"
    )
    monkeypatch.setattr(ha, "datetime", FixedDatetime)
    results = convert_completed_logs(
        log_dir, output_dir, timezone_name="America/Los_Angeles"
    )
    assert results == ()
    assert not (output_dir / "historical_analysis_2026-08-22.md").exists()
